### ISSUE TITLE
Support for script tags other than javascript

### ISSUE THREAD

**Issue by lionelbrits** [migliori/ajax-fetch-data-loader#1]
Some applications use the script tag for stuff other than javascript. Recommend changing
```
script.type = 'text/javascript';
```
to
```
// copy type
if(element.type)
            script.type = element.type;
```
since modern HTML5 will just assume application/javascript if the type is omitted.

Also there are other edge cases to consider here... For example, the script might have other attributes (such as id) which should be copied over. Thus:
```
[...element.attributes].forEach( attr => { script.setAttribute(attr.nodeName ,attr.nodeValue) })
```
The forEach should probably be replaced with a c-style loop for maximum backwards compatibility. Or something like:
```
// clone attributes
Array.prototype.forEach.call(element.attributes, function (attr) {
            script.setAttribute(attr.nodeName ,attr.nodeValue);
});
```

**Comment by migliori** [comment]
@lionelbrits Thank you for the relevant suggestions; I have updated the code
