### ISSUE TITLE
Issue when load the exact same <script src="src/to/path/file.js"></script>

### ISSUE THREAD

**Issue by triawarman** [migliori/ajax-fetch-data-loader#3]
Hy thanks for this code, its helps me.

I got a problem, when  fetch a page then insert to current page that already have the exact same <script src="src/to/path/file.js"></script> loaded, my worked js scripts is not work.

then tried to modified your code from line 52 to 58
https://github.com/migliori/ajax-fetch-data-loader/blob/79978f8f529be21a16d0993a98f90f6560b8bc09/fetch-data-loader.js#L52

to
```javascript

  script.src = element.src;
  script.onload = function () {
      /*_loadContent(data, index + 1, container);*/
  };
  if(document.querySelector('script[src="'+element.src+'"]') === undefined) {
      document.head.appendChild(script);
  }
  _loadContent(data, index + 1, container);
```
this solves my problem.

but im sure, maybe, still face unseen issue like `<script> doSomething1() {} </script>` that already loaded then the new page insert the exact same script function.

oh btw what these line do ?, i dont understand what it does, so i commented
```javascript
script.onload = function () {
    _loadContent(data, index + 1, container);
};
```

**Comment by migliori** [comment]
Hi,

The `loadData` function calls the `_htmlToElements`, which organises the data into 2 arrays: `nodesArray` and `scriptsArray`
Then it sends these 2 arrays of elements to `_loadContent`

The `_loadContent` is recursive. It walks through each array, first the nodes, then the scripts, and add them to the DOM.

```
    script.onload = function () {
      _loadContent(data, index + 1, container);
  };
```

This part waits for the script to be loaded, then calls _loadContent to load the next script.
If you comment it your last scripts won't be loaded.

```
  if(document.querySelector('script[src="'+element.src+'"]') === undefined) {
      document.head.appendChild(script);
  }
```

This part of the code search into your origin page for a script with the same source as the current one.
If it finds it it won't insert the new script, to avoid loading twice the same scripts.

So if your scripts have (exactly) the same source they won't be loaded twice.

I hope it'll help you.

**Comment by triawarman** [comment]
```javascript
script.onload = function () {
      /*_loadContent(data, index + 1, container);*/
  };
```
i should uncomment this one, and rewrite line 52 to 58.

thanks bro.
